### ISSUE TITLE
List-Styles configurable per element

### ISSUE THREAD

**Issue by PRGfx** [nlx-lars/list-style#3]
I tried around a bit with
```yaml
editorOptions:
  formatting:
    listStyle: boolean|null|{ol?: boolean|null|string[]|Record<string, boolean|null>, ul?: ...}
```
but I think this is not very readable. I think I would prefer a separate editor option:
```yaml
editorOptions:
  listStyle:
    ol: boolean|null|string[]|Record<string, boolean|null>
    ul: boolean|null|string[]|Record<string, boolean|null>
```

With
* `true` all available values
* `false|null` none of these (only default? maybe no menu if only default is available, but maybe it should be possible to select the list and revert to default..)
* `string[]` a list of enabled keys from the `Lala.ListStyle.styles.{listType}` setting
* `Record<string, boolean|null>` a dictionary of keys from the setting and whether they should be enabled or not

Is there a preferred configuration?

**Comment by paxuclus** [comment]
@PRGfx my preference would be the second option. I tend to only allow `boolean` and  `Record<string, boolean|null>` though, as that is easier to override in sub nodetypes.

```yaml
editorOptions:
  listStyle:
    ol: false
    ul:
      circle: true
      square: false
```
